### ISSUE TITLE
Own bundle not working

### ISSUE THREAD

**Issue by Geelik** [davidsosavaldes/Codeigniter-Bundle#1]
Hello,

I can't figure out how to make my own bundle. I only get 404 errors.
So after successfully installed this library, i created this files : 
- application/bundles/dashboard
- application/bundles/dashboard/config/routes.php

```php 
$route['dashboard'] = 'Dashboard';
```

- application/bundles/dashboard/controllers/Dashboard.php

```php 
class Dashboard extends Bundle_Controller{

    public function index(){
        echo 'dashboard';
    }
}
```

- application/config/bundles.php

```php 
$config['bundles'] = array(
    'dashboard' => array(
        'location' => 'dashboard',
        'route' => 'dashboard',
        'default' => false
    )
);
```

**Comment by davidsosavaldes** [comment]
Your router file is the problem, you need to declare all your routes in lowercase, here's an example:

	$route['entrust']                   = 'dashboard'; 
	$route['entrust/logout']            = 'login/logout';
	$route['entrust/users']             = 'user/index';
	$route['entrust/api/cerberus/(.+)'] = 'cerberus/$1';	

	/* End of file routes.php */
	/* Location: .bundles/EntrustBundle/config/routes.php */

[EntrustBundle](https://github.com/davidsosavaldes/Codeigniter-Bundle-Entrust) is an example of how to use this library, it's incomplete so don't install it in your application.

**Comment by Geelik** [comment]
How i see now, i thought routes worked like hmvc, where routes autoload with methods name.
Thank for your answer.
